//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int Id { get; set; }
        public string TransType { get; set; }
        public int ClientID { get; set; }
        public System.DateTime TransportDate { get; set; }
        public int WarehouseId { get; set; }
        public int UserID { get; set; }
    
        public virtual SuppliersClient SuppliersClient { get; set; }
        public virtual User User { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
